[project]
name = "day3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "vivek", email = "vivekrajraghav@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "groq>=1.7.0",
    "python-dotenv>=1.2.3",
]

[project.scripts]
day3 = "day3:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "venv",
]
