[project]
name = "day1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "vivek", email = "vivekrajraghav@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "groq>=1.7.0",
    "python-dotenv>=1.2.3",
]

[project.scripts]
day1 = "day1:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
